# Generated by Django 4.2.16 on 2025-01-28 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=300)),
                ('sobrenome', models.CharField(default='', max_length=200)),
                ('cutter', models.CharField(default='', help_text='Clique no <a href="https://www.tabelacutter.com" target="_blank">link da Tabela Cutter</a> para gerar o Cutter e insira o valor gerado neste campo.', max_length=20)),
                ('titulo', models.CharField(default='', max_length=300)),
                ('sub_titulo', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('curso', models.CharField(default='', max_length=300)),
                ('campus', models.CharField(default='', max_length=300)),
                ('instituicao', models.CharField(default='', max_length=300, verbose_name='Instituição')),
                ('cidade', models.CharField(default='', max_length=100)),
                ('ano', models.PositiveIntegerField(default='')),
                ('folhas', models.PositiveIntegerField(default=1)),
                ('figuras', models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='Sim', max_length=20)),
                ('referencias', models.PositiveIntegerField(default=1)),
                ('anexos', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('encardenacao', models.CharField(choices=[('Brochura', 'Brochura'), ('Espiral', 'Espiral')], default='Brochura', max_length=20)),
                ('orientador', models.CharField(default='', max_length=200)),
                ('genero_orientador', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=20)),
                ('titulo_orientador', models.CharField(choices=[('Especialista', 'Especialista'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], default='Mestre', max_length=50)),
                ('coorientador', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('genero_coorientador', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20, null=True)),
                ('titulo_coorientador', models.CharField(blank=True, choices=[('Especialista', 'Especialista'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=50, null=True)),
                ('tipo_trabalho', models.CharField(choices=[('Monografia', 'Monografia'), ('Dissertação', 'Dissertação'), ('Tese', 'Tese'), ('Tcc', 'TCC'), ('Produto Educacional', 'Produto Educacional')], default='Monografia', max_length=19, verbose_name='Tipo do Trabalho')),
                ('titulo_obtido', models.CharField(choices=[('Especialista', 'Especialista'), ('Bacharel', 'Bacharel'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], default='Bacharelado', max_length=15)),
                ('assunto1', models.CharField(default='Curso X', max_length=100)),
                ('assunto2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('assunto3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('assunto4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('assunto5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fonte', models.CharField(choices=[('Arial', 'Arial'), ('Times', 'Times New Roman')], default='Times', max_length=15)),
                ('tamanho_fonte', models.PositiveIntegerField(default=11, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(9)])),
            ],
        ),
    ]
