# Generated by Django 4.2.16 on 2025-01-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='identificacao',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
