# Generated by Django 4.2.16 on 2025-01-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0002_ficha_identificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='identificacao',
        ),
    ]
